### ISSUE TITLE
Most simple metadata query

### ISSUE THREAD

**Issue by sekruse** [stratosphere/metadata-ms#5]
The intention of this issue is mainly to bootstrap the analytics layer for the MDMS. Specifically, at least the following tasks should be accomplished:

- [x] add a Scala-based maven module for analytics
- [ ] create some kind of infrastructure to formulate metadata queries, inclusive of the metadata sources (see `ConstraintCollection`), operators, and a presentation layer/result consumer
- [ ] deploy queries using Flink (see `mdms-flink` for existing utilities)
- [x] query that should be supported for now: `SELECT * FROM constraint collection with ID x WHERE type=y` (please don't implement this syntax :wink:), i.e., retrieve all constraints with a certain type that belong to a certain constraint collection

**Comment by lawrencebenson** [comment]
The query can now be called by the following:

    mds.getConstraintCollection(<ID>).allOfType(<Constraint Class>)

where `mds` is a `MetadataStore` object.
