### ISSUE TITLE
Useful representation of Constraints

### ISSUE THREAD

**Issue by lawben** [stratosphere/metadata-ms#8]
Each `Constraint` should have a useful `toString()` method implemented, e.g. 
```java
@Override
public String toString() {
    return "Reference [dependentColumns=" + Arrays.toString(dependentColumns) 
           + ", referencedColumns=" + Arrays.toString(referencedColumns) + "]";
}
  ```            
`ColumnStatistics` only return `de.hpi.isg.mdms.domain.constraints.ColumnStatistics@3f3c966c`, which is not helpful. 

This is needed to represent objects in charts or tables in a correct manner.

**Comment by sekruse** [comment]
`Constraint`s can be formatted using a `DependencyPrettyPrinter`.
